FROM python:3.11
WORKDIR /usr/app

COPY src/requirements.txt requirements.txt

ARG TAMARIX_GITHUB_TOKEN
ENV TAMARIX_GITHUB_TOKEN=${TAMARIX_GITHUB_TOKEN}
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip install --upgrade "langgraph-cli[inmem]"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    poppler-utils \
    default-jre && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .
ENV PUBLIC_ENV=dev
CMD langgraph dev --allow-blocking --host 0.0.0.0 --port 2024
